repos:
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.28.0
    hooks:
      - id: gitleaks
  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black
        args: [--config=pyproject.toml]
  - repo: https://github.com/pycqa/isort
    rev: 6.0.1
    hooks:
      - id: isort
        args: [--profile=black]
  - repo: https://github.com/pycqa/flake8
    rev: 7.3.0
    hooks:
      - id: flake8
  - repo: local
    hooks:
      - id: git-secrets
        name: Git Secrets
        description: git-secrets scans commits, commit messages, and --no-ff merges to prevent adding secrets into your git repositories.
        entry: powershell
        args: [-ExecutionPolicy, Bypass, -File, nhsd-git-secrets/pre-commit.ps1]
        language: system
        always_run: true
